name=Crucible
version=0.0.1
additionalVersions=
className=io.github.crucible.bootstrap.rfb.CrucibleRfbPlugin
transformerExclusions=io.github.crucible.bootstrap.rfb
versionConstraints=
loadBefore=
loadAfter=
loadRequires=
