name: Sync From Wiki

on:
  workflow_dispatch:

#   schedule:
#     - cron: '30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Sync
        run: |
          git remote add wiki https://github.com/CrucibleMC/Crucible.wiki.git
          git fetch wiki
          git pull wiki master
          git push origin wiki
