name: Sync To Wiki

on:
  push:
    branches: [ wiki ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add wiki https://github.com/CrucibleMC/Crucible.wiki.git
          git push wiki HEAD:master
